In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Datasets/Datasets/Twitter_Full.csv',sep=";")
df.head()

,text,hashtags,labels,Unnamed: 3,Unnamed: 4
0,Being s mom is cleaning 24/7 the same shit ove...,"['momlife', 'kids', 'tired']",1,NaN,NaN
1,And now we have been given the walkthru book b...,['walkthru'],0,NaN,NaN
2,Wishing YOU Peace Joy & Love! JoyTrain MentalH...,"['Peace', 'Joy', 'Love', 'JoyTrain', 'MentalHe...",0,NaN,NaN
3,speak-no-evil monkey Can I Be Honest With You...,"['therapy', 'help', 'NLP', 'CBT', 'hypnotherap...",1,NaN,NaN
4,Psy Do u hv any regrets? Me No Psy Are you hap...,[],0,NaN,NaN

In [ ]:
df.drop(["hashtags","Unnamed: 3","Unnamed: 4"],axis=1,inplace=True)
df

                                                   text  labels
0     Being s mom is cleaning 24/7 the same shit ove...       1
1     And now we have been given the walkthru book b...       0
2     Wishing YOU Peace Joy & Love! JoyTrain MentalH...       0
3      speak-no-evil monkey Can I Be Honest With You...       1
4     Psy Do u hv any regrets? Me No Psy Are you hap...       0
...                                                 ...     ...
8895  Thank you for all your business questions toda...       0
8896  Who is planning on walking their minds today?!...       1
8897   no mobile phones Three Tips to Reduce Technos...       1
8898   purple heart Day 1 purple heart But vets firs...       1
8899  This is exactly what Bella did to me last nigh...       1

[8900 rows x 2 columns]

In [ ]:
df.isnull().sum()

text      3
labels    0
dtype: int64

In [ ]:
df.dropna(inplace=True)
df.isnull().sum()

text      0
labels    0
dtype: int64

In [ ]:
df.dtypes

text      object
labels     int64
dtype: object

In [ ]:
df.duplicated().sum()

np.int64(461)

In [ ]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [ ]:
df

                                                   text  labels
0     Being s mom is cleaning 24/7 the same shit ove...       1
1     And now we have been given the walkthru book b...       0
2     Wishing YOU Peace Joy & Love! JoyTrain MentalH...       0
3      speak-no-evil monkey Can I Be Honest With You...       1
4     Psy Do u hv any regrets? Me No Psy Are you hap...       0
...                                                 ...     ...
8894  A FAMILY THAT TRAVELS TOGETHER IS ALWAYS A HAP...       0
8896  Who is planning on walking their minds today?!...       1
8897   no mobile phones Three Tips to Reduce Technos...       1
8898   purple heart Day 1 purple heart But vets firs...       1
8899  This is exactly what Bella did to me last nigh...       1

[8436 rows x 2 columns]

In [ ]:
df.reset_index(drop=True,inplace=True)
df

                                                   text  labels
0     Being s mom is cleaning 24/7 the same shit ove...       1
1     And now we have been given the walkthru book b...       0
2     Wishing YOU Peace Joy & Love! JoyTrain MentalH...       0
3      speak-no-evil monkey Can I Be Honest With You...       1
4     Psy Do u hv any regrets? Me No Psy Are you hap...       0
...                                                 ...     ...
8431  A FAMILY THAT TRAVELS TOGETHER IS ALWAYS A HAP...       0
8432  Who is planning on walking their minds today?!...       1
8433   no mobile phones Three Tips to Reduce Technos...       1
8434   purple heart Day 1 purple heart But vets firs...       1
8435  This is exactly what Bella did to me last nigh...       1

[8436 rows x 2 columns]

In [ ]:
counts=df['labels'].value_counts()
percentages = df['labels'].value_counts(normalize=True) * 100

print("Counts:\n", counts)
print("\nPercentages:\n", percentages)

Counts:
 labels
1    4307
0    4129
Name: count, dtype: int64

Percentages:
 labels
1    51.055002
0    48.944998
Name: proportion, dtype: float64

In [ ]:
Text=df.text
Text

0       Being s mom is cleaning 24/7 the same shit ove...
1       And now we have been given the walkthru book b...
2       Wishing YOU Peace Joy & Love! JoyTrain MentalH...
3        speak-no-evil monkey Can I Be Honest With You...
4       Psy Do u hv any regrets? Me No Psy Are you hap...
                              ...
8431    A FAMILY THAT TRAVELS TOGETHER IS ALWAYS A HAP...
8432    Who is planning on walking their minds today?!...
8433     no mobile phones Three Tips to Reduce Technos...
8434     purple heart Day 1 purple heart But vets firs...
8435    This is exactly what Bella did to me last nigh...
Name: text, Length: 8436, dtype: object

In [ ]:
Text=Text.str.replace("[^a-zA-z0-9 ]","",regex=True)
Text

0       Being s mom is cleaning 247 the same shit over...
1       And now we have been given the walkthru book b...
2       Wishing YOU Peace Joy  Love JoyTrain MentalHea...
3        speaknoevil monkey Can I Be Honest With You g...
4       Psy Do u hv any regrets Me No Psy Are you happ...
                              ...
8431    A FAMILY THAT TRAVELS TOGETHER IS ALWAYS A HAP...
8432    Who is planning on walking their minds today w...
8433     no mobile phones Three Tips to Reduce Technos...
8434     purple heart Day 1 purple heart But vets firs...
8435    This is exactly what Bella did to me last nigh...
Name: text, Length: 8436, dtype: object

In [ ]:
from nltk import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [ ]:
import nltk

In [ ]:
nltk.download('punkt_tab')
nltk.download('wordnet')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [ ]:
Text=Text.apply(lambda line:[lemmatizer.lemmatize(word.lower()) for word in nltk.word_tokenize(line)]).apply(lambda token:" ".join(token))
Text

0       being s mom is cleaning 247 the same shit over...
1       and now we have been given the walkthru book b...
2       wishing you peace joy love joytrain mentalheal...
3       speaknoevil monkey can i be honest with you gl...
4       psy do u hv any regret me no psy are you happy...
                              ...
8431    a family that travel together is always a happ...
8432    who is planning on walking their mind today wo...
8433    no mobile phone three tip to reduce technostre...
8434    purple heart day 1 purple heart but vet first ...
8435    this is exactly what bella did to me last nigh...
Name: text, Length: 8436, dtype: object

Removing stop word

In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')
sw=stopwords.words('english')
print(sw)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
Text=Text.apply(lambda line:[word for word in nltk.word_tokenize(line) if word not in sw]).apply(lambda token:" ".join(token))
Text

0       mom cleaning 247 shit end result everything me...
1       given walkthru book base whole school pd grinn...
2       wishing peace joy love joytrain mentalhealth q...
3       speaknoevil monkey honest globe showing europe...
4       psy u hv regret psy happy yes feel relieved go...
                              ...
8431    family travel together always happy family red...
8432    planning walking mind today woman walking red ...
8433    mobile phone three tip reduce technostress key...
8434    purple heart day 1 purple heart vet first dogs...
8435    exactly bella last night also favorite episode...
Name: text, Length: 8436, dtype: object

Vectorisation

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()

In [ ]:
x=vectorizer.fit_transform(Text)
x

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 141008 stored elements and shape (8436, 23680)>

In [ ]:
x=x.toarray()
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
y=df['labels']
y

0       1
1       0
2       0
3       1
4       0
       ..
8431    0
8432    1
8433    1
8434    1
8435    1
Name: labels, Length: 8436, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [ ]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()
LR.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_pred1=LR.predict(x_test)
y_pred1

array([1, 1, 1, ..., 0, 1, 1])

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.88      0.75      0.81      1284
           1       0.77      0.89      0.83      1247

    accuracy                           0.82      2531
   macro avg       0.83      0.82      0.82      2531
weighted avg       0.83      0.82      0.82      2531

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
KNN=KNeighborsClassifier()
KNN.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred2=KNN.predict(x_test)
y_pred2

array([1, 0, 0, ..., 0, 1, 0])

In [ ]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.76      0.69      0.72      1284
           1       0.71      0.77      0.74      1247

    accuracy                           0.73      2531
   macro avg       0.73      0.73      0.73      2531
weighted avg       0.73      0.73      0.73      2531

In [ ]:
from sklearn.svm import LinearSVC
SVC=LinearSVC()
SVC.fit(x_train,y_train)

LinearSVC()

In [ ]:
y_pred3=SVC.predict(x_test)
y_pred3

array([1, 1, 1, ..., 0, 1, 1])

In [ ]:
print(classification_report(y_test,y_pred3))

              precision    recall  f1-score   support

           0       0.86      0.79      0.82      1284
           1       0.80      0.87      0.83      1247

    accuracy                           0.83      2531
   macro avg       0.83      0.83      0.83      2531
weighted avg       0.83      0.83      0.83      2531

In [ ]:
from sklearn.naive_bayes import MultinomialNB
MNB=MultinomialNB()
MNB.fit(x_train,y_train)

MultinomialNB()

In [ ]:
y_pred4=MNB.predict(x_test)
y_pred4

array([1, 1, 1, ..., 0, 1, 1])

In [ ]:
print(classification_report(y_test,y_pred4))

              precision    recall  f1-score   support

           0       0.84      0.73      0.78      1284
           1       0.76      0.86      0.80      1247

    accuracy                           0.79      2531
   macro avg       0.80      0.79      0.79      2531
weighted avg       0.80      0.79      0.79      2531

In [ ]:
from sklearn.tree import DecisionTreeClassifier
DTC=DecisionTreeClassifier(max_depth=20,random_state=1) #by default gini
DTC.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=20, random_state=1)

In [ ]:
y_pred5=DTC.predict(x_test)
y_pred5

array([1, 1, 1, ..., 1, 1, 0])

In [ ]:
print(classification_report(y_test,y_pred5))

              precision    recall  f1-score   support

           0       0.85      0.65      0.74      1284
           1       0.71      0.88      0.79      1247

    accuracy                           0.77      2531
   macro avg       0.78      0.77      0.76      2531
weighted avg       0.78      0.77      0.76      2531

In [ ]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier

In [ ]:
RF=RandomForestClassifier()
RF.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred6=RF.predict(x_test)
y_pred6

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
print(classification_report(y_test,y_pred6))

              precision    recall  f1-score   support

           0       0.87      0.71      0.78      1284
           1       0.75      0.89      0.81      1247

    accuracy                           0.80      2531
   macro avg       0.81      0.80      0.80      2531
weighted avg       0.81      0.80      0.80      2531

In [ ]:
ADA=AdaBoostClassifier()
ADA.fit(x_train,y_train)

AdaBoostClassifier()

In [ ]:
y_pred7=ADA.predict(x_test)
y_pred7

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
print(classification_report(y_test,y_pred7))

              precision    recall  f1-score   support

           0       0.89      0.54      0.67      1284
           1       0.66      0.93      0.78      1247

    accuracy                           0.73      2531
   macro avg       0.78      0.74      0.72      2531
weighted avg       0.78      0.73      0.72      2531

In [ ]:
GB=GradientBoostingClassifier()
GB.fit(x_train,y_train)

GradientBoostingClassifier()

In [ ]:
y_pred8=GB.predict(x_test)
y_pred8

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
print(classification_report(y_test,y_pred8))

              precision    recall  f1-score   support

           0       0.88      0.66      0.76      1284
           1       0.72      0.91      0.80      1247

    accuracy                           0.78      2531
   macro avg       0.80      0.78      0.78      2531
weighted avg       0.80      0.78      0.78      2531

In [ ]:
XGB=XGBClassifier()
XGB.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
y_pred9=XGB.predict(x_test)
y_pred9

array([1, 1, 1, ..., 1, 1, 0])

In [ ]:
print(classification_report(y_test,y_pred9))

              precision    recall  f1-score   support

           0       0.85      0.73      0.79      1284
           1       0.76      0.87      0.81      1247

    accuracy                           0.80      2531
   macro avg       0.81      0.80      0.80      2531
weighted avg       0.81      0.80      0.80      2531

In [ ]:
from sklearn.metrics import accuracy_score
LR_accuracy=accuracy_score(y_test,y_pred1)
KNN_accuracy=accuracy_score(y_test,y_pred2)
SVC_accuracy=accuracy_score(y_test,y_pred3)
MNB_accuracy=accuracy_score(y_test,y_pred4)
DTC_accuracy=accuracy_score(y_test,y_pred5)
RF_accuracy=accuracy_score(y_test,y_pred6)
ADA_accuracy=accuracy_score(y_test,y_pred7)
GB_accuracy=accuracy_score(y_test,y_pred8)
XGB_accuracy=accuracy_score(y_test,y_pred9)

In [ ]:
accuracies=pd.DataFrame({
    'Model':['Logistic Regression','KNN','SVC','MNB','Decision Tree','Random Forest','ADA','Gradient Boosting','XGB'],
    'Accuracy':[LR_accuracy,KNN_accuracy,SVC_accuracy,MNB_accuracy,DTC_accuracy,RF_accuracy,ADA_accuracy,GB_accuracy,XGB_accuracy]
})

In [ ]:
print(accuracies)

                 Model  Accuracy
0  Logistic Regression  0.818649
1                  KNN  0.730541
2                  SVC  0.826946
3                  MNB  0.792967
4        Decision Tree  0.766495
5        Random Forest  0.799684
6                  ADA  0.733307
7    Gradient Boosting  0.783090
8                  XGB  0.799684

In [ ]:
import pickle
pickle.dump(SVC,open('model.sav','wb'))

In [ ]:
pickle.dump(vectorizer,open('vectorizer.sav','wb'))